name: Tests
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test_sqlite:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        gemfile: ["rails_7.1", "rails_7.2"]
        ruby: ["3.1", "3.2", "3.3"]

    steps:
      - uses: actions/checkout@v4

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.sqlite3.gemfile

      - name: Run tests
        run: |
          #bundle exec rake db:test:prepare
          bundle exec rake
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.sqlite3.gemfile
